// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recipes.Models;

namespace Recipes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181207200307_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Recipes.Models.AddedRecipes", b =>
                {
                    b.Property<int>("RecipeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Rating");

                    b.Property<string>("description")
                        .IsRequired();

                    b.Property<string>("ingredient1")
                        .IsRequired();

                    b.Property<string>("ingredient2")
                        .IsRequired();

                    b.Property<string>("ingredient3")
                        .IsRequired();

                    b.Property<string>("ingredient4")
                        .IsRequired();

                    b.Property<string>("ingredient5")
                        .IsRequired();

                    b.Property<string>("recipename")
                        .IsRequired();

                    b.HasKey("RecipeID");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Recipes.Models.AddedReviews", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Rating");

                    b.Property<int?>("RecipeID");

                    b.Property<string>("addreview")
                        .IsRequired();

                    b.HasKey("ReviewID");

                    b.HasIndex("RecipeID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Recipes.Models.AddedReviews", b =>
                {
                    b.HasOne("Recipes.Models.AddedRecipes", "Recipe")
                        .WithMany("Reviews")
                        .HasForeignKey("RecipeID");
                });
#pragma warning restore 612, 618
        }
    }
}
